version: '3.8'

services:
  postgres:
    image: postgres:17  # Updated to the latest PostgreSQL 17 release
    container_name: my_postgres_cricket_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cricketapp
      POSTGRES_DB: cricketapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
